<a href="https://colab.research.google.com/github/lord-00121/ML-LAB/blob/main/lab%2010.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
from tensorflow.keras.utils import to_categorical

# Load and reshape
data = pd.read_csv("/content/Iris.csv", header=None, names=["sl", "sw", "pl", "pw", "sp"], skiprows=1)
encoder = LabelEncoder()
y = to_categorical(encoder.fit_transform(data["sp"]))
X = data.drop("sp", axis=1).values

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# 1D CNN reshaping
X_train_reshaped = X_train_scaled.reshape(X_train_scaled.shape[0], X_train_scaled.shape[1], 1)
X_test_reshaped = X_test_scaled.reshape(X_test_scaled.shape[0], X_test_scaled.shape[1], 1)
# Preprocessing and reshaping complete.
# X_train_reshaped shape: (120, 4, 1)

In [7]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv1D, MaxPooling1D, Flatten, Dense

model = Sequential([
    Conv1D(32, kernel_size=2, activation='relu', input_shape=(4, 1)),
    MaxPooling1D(pool_size=2),
    Flatten(),
    Dense(16, activation='relu'),
    Dense(3, activation='softmax')
])
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])
history = model.fit(X_train_reshaped, y_train, epochs=50, batch_size=5, verbose=0)


/usr/local/lib/python3.12/dist-packages/keras/src/layers/convolutional/base_conv.py:113: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [8]:
from sklearn.metrics import accuracy_score, confusion_matrix
y_pred = np.argmax(model.predict(X_test_reshaped), axis=1)
y_true = np.argmax(y_test, axis=1)
print(f"Accuracy: {accuracy_score(y_true, y_pred):.4f}")
print("\nConfusion Matrix:\n", confusion_matrix(y_true, y_pred))



1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 127ms/step
Accuracy: 0.7667

Confusion Matrix:
 [[7 3 0]
 [1 8 0]
 [2 1 8]]
